### ISSUE TITLE
API/Rate Limits/Promises

### ISSUE THREAD

**Issue by GetchaPopcornReady** [addaleax/promise-ratelimit#1]
I am new to using APIs and this is my first time using promises to make sure that each function properly is called and then also rate limiting. This method is in a loop so it keeps getting called and needs limited. Ive been trying various types of npms but haven't fully understood how to use any.

Heres a snip it of my code:

general promise function:

```js
function requestPromise(uri) {
  //console.log('attempting: ' + uri);
  return new Promise(function(resolve, reject) {
    request(uri) .then(function (response) {
      var json = JSON.parse(response);
      resolve(json); //return parsed json object as a promise. Evaluate again with '.then'
    }) .catch(function (err) {
      reject(new Error('error reaching endpoint: ' + uri));
    });
  });
}
```

Method declaration calling the API:

```js
function getMatchData(gameID){
  var uri = 'https://na1.api.riotgames.com/lol/match/v3/matches/' + gameID + '?api_key=' + apiKey;
  return requestPromise(uri);
}
```

Invoking the method:

```js
getMatchData(gameID)
.then(function(match){

                   //do something
})
.catch(function (err) {
console.log('err: ' + err);
});
```

Thank you in advance!

**Comment by addaleax** [comment]
Hi! I’ve wrapped and indented some of your code in ```` ```js ```` tags to make it a bit more readable. :)

It sounds like creating a `throttle` like in the README of this project would help you; you could replace `requestPromise(uri)` with `throttle().then(() => requestPromise(uri))` in that case to limit the number of spawned `requestPromise`s per time.

**Comment by GetchaPopcornReady** [comment]
thanks that worked!!!
